Fix/location editing
MCLD/ocuda pull request #311
Opened 2021-05-24 23:35 UTC by k7hpn

- Manage location-related segments directly from the location page
- Manage location social cards directly from the location page

2021-05-26 19:56 UTC, madison-boman requested changes
I have just a few comments on this, overall it looks great!

2021-05-26 19:56 UTC, madison-boman commented on src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
> +                if (geoResult?.Results?.Count() > 0)
Should we be using the `.Length` rather than `.Count()` ?

2021-05-26 19:56 UTC, madison-boman commented on src/Ops.Controllers/Areas/SiteManagement/LocationsController.cs
> +                            "Please select an Close Time.");
Should read _"Please select a Close Time."_

2021-05-26 19:56 UTC, madison-boman commented on src/Ops.Web/Areas/SiteManagement/Views/Locations/LocationDetails.cshtml
> +            HandleGoogleLocations(locations);
Not sure if the document wasn't formatted or, if these just need to be indented for readability.

2021-05-27 02:40 UTC, iafb requested changes
- Saving location details removes saved values for structured data, segments and social cards
- Location structured data field "Is Accessible For Free" value doesn't save


The following Location fields should probably have a DisplayName assigned;
- MapLink
- EventLink
- SubscriptionLink
- AdministrativeArea
- AreaServedName
- AreaServedType
- ParentOrganization
- PriceRange

2021-05-27 18:31 UTC, merged